spin_manifest_version = 2

[application]
name = "hello-wasm-spin"
version = "0.1.0"
authors = ["Naosuke Ito"]
description = ""

[[trigger.http]]
route = "/..."
component = "hello-wasm-spin"

[component.hello-wasm-spin]
source = "target/wasm32-wasi/release/hello_wasm_spin.wasm"
allowed_outbound_hosts = []
[component.hello-wasm-spin.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
